language: node_js
node_js:
- '8'
install:
- npm i
script:
- npm run lint
- npm run build
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
- provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
